global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'argo-api'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'
    
  - job_name: 'argo-signal-generator'
    static_configs:
      - targets: ['argo-signal-generator-blue:8001']
      
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
